# Generated by Django 4.1.3 on 2022-11-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={'verbose_name_plural': 'University Campuses'},
        ),
    ]
